print ("conten-type:text/html\r\n\r\n")
print ('<html>')
print ('<head>')
print ('<title>hello vikash </title>')
print ('</head>')
print ('<body>')
print ('<h3> hello programmer welcome to cgi programming </h3>')
print ('</body>')
print ('</html>')
